apiVersion: v1
kind: Service
metadata:
  name: {{ include "autogenstudio.fullname" . }}-app
  labels:
    {{- include "autogenstudio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appService.type }}
  ports:
    - port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "autogenstudio.selectorLabels" . | nindent 4 }}