apiVersion: agent.ai.solo.io/v1alpha1
kind: AutogenModelConfig
metadata:
  name: default-model-config
  labels:
    {{- include "autogenstudio.labels" . | nindent 4 }}
spec:
  apiKeySecretName: {{ .Values.openai.secretName }}
  apiKeySecretKey: {{ .Values.openai.secretKey }}
  model: gpt-4o