apiVersion: v1
kind: Service
metadata:
  name: {{ include "autogenstudio.fullname" . }}-app
  labels:
    {{- include "autogenstudio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "autogenstudio.selectorLabels" . | nindent 4 }}