apiVersion: ai.solo.io/v1alpha1
kind: AutogenTeam
metadata:
  name: pod-scaling-team
  namespace: autogen-system
spec:
  teamName: "pod-scaling-team"
  maxChatRounds: 50
  selector:
    matchLabels:
      team: pod-scaling
---
apiVersion: ai.solo.io/v1alpha1
kind: AutogenAgent
metadata:
  name: task-planner
  namespace: autogen-system
  labels:
    team: pod-scaling
spec:
  name: "TaskPlanner"
  type: "planner"
  description: "An agent for planning tasks, this agent should be the first to engage when given a new task."
  systemMessage: |
    You are a planning agent.
    Your job is to break down complex tasks into smaller, manageable subtasks.
    Your team members are:
        k8s_agent: Run information gathering tasks related to Kubernetes and any resources in the cluster.
        istio_agent: Run information gathering tasks related to Istio.

    You only plan and delegate tasks - you do not execute them yourself.

    When assigning tasks, use this format:
    1. <agent> : <task>

    After all tasks are complete, summarize the findings and end with "TERMINATE".
---
apiVersion: ai.solo.io/v1alpha1
kind: AutogenAgent
metadata:
  name: k8s_agent
  namespace: autogen-system
  labels:
    team: pod-scaling
spec:
  name: "k8s_agent"
  type: "k8s_agent"
  builtinTools:
  - k8s.get_pods
  - k8s.get_pod
  - k8s.get_services
  - k8s.get_resources
  - k8s.get_pod_logs
  description: "Run information gathering tasks related to Kubernetes and any resources in the cluster"
  systemMessage: |
    You are an agent specialized in Kubernetes.
    You have access to tools that allow you to interact with the Kubernetes cluster.
---
apiVersion: ai.solo.io/v1alpha1
kind: AutogenAgent
metadata:
  name: istio_agent
  namespace: autogen-system
  labels:
    team: pod-scaling
spec:
  name: "istio_agent"
  type: "istio_agent"
  builtinTools:
  - istio.proxy_config
  description: "Run information gathering tasks related to Istio"
  systemMessage: |
    You are an agent specialized in Istio.
    You have access to the proxy_config tool which allows you to get the proxy configuration for a pod.