[project]
name = "kagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "autogen-core==0.4.2",
  "autogen-ext==0.4.2",
  "autogen-agentchat==0.4.2",
  "ruff>=0.9.2",
]

