[project]
name = "kagent"
version = "0.0.1"
license = {file = "LICENSE-CODE"}
description = "AutoGen agents and teams library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "autogen-agentchat==0.4.2",
  "autogen-core==0.4.2",
  "autogen-ext==0.4.2"
]