[project]
name = "kagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "autogen-core==0.4.2",
  "autogen-ext==0.4.2",
  "autogen-agentchat==0.4.2",
  "openai==1.60.0",
  "tiktoken==0.8.0",
  "ruff>=0.9.2",
  "python-dotenv>=1.0.1"
]

[tool.ruff]
line-length = 120
fix = true

target-version = "py310"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "W", "B", "Q", "I", "ASYNC", "T20"]
ignore = ["F401", "E501"]